# Generated by Django 5.1.6 on 2025-03-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user1',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
