# Generated by Django 5.1.6 on 2025-03-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_user1_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user1',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
